### PR TITLE
Hw08, Igor Engel

### PR DESCRIPTION
**Pull request by gt22**

### CODE REVIEW

**Comment by kajigor** [comment]
Small comments: 

The tests fail to build and run. 
No tests for the Hindley-Milner.
The app demands `-o` flag but does not use in case of Hindley-Milner type inference.

**Comment by kajigor** [comment]
Bigger issue: having explicit types in abstractions makes no sense, because you ignore them: 

```
ev@ev:~/teach/2023/students/IgorEngel/stlc$ stack run exe -- -h -i "(\\x:a.x)(\\x:a.x)" -o result.tex
Ok
x1 -> x1
ev@ev:~/teach/2023/students/IgorEngel/stlc$ stack run exe -- -h -i "(\\x:a.x)(\\x:a->a.x)" -o result.tex
Ok
x1 -> x1
ev@ev:~/teach/2023/students/IgorEngel/stlc$ stack run exe -- -h -i "(\\x:Bool.x)(\\x:a.x)" -o result.tex
Ok
x1 -> x1
```

You should either remove the type specifications, or better yet, make sure that the type you infer corresponds to the user-specified.

**Comment by gt22** [comment]
Types in abstraction are used by normal typechecker, so can't be removed. And ignoring them is the algorithm from the lecture doesn't use them, it was unclear whether the implementation should

**Comment by kajigor** [comment]
Well, you can modify the parser so that the type is optional, and you only run old typecheker if the types are specified everywhere, and HM is only run when none is specified.

**Pull request closed without merging**
