### PR TITLE
Hw07 Razvan Perial

### PR DESCRIPTION
**Pull request by razvanperial**

### CODE REVIEW

**Comment by kajigor** [comment]
I have a strong suspicion that this homework was copied from Tea.

**Comment by razvanperial** [comment]
> I have a strong suspicion that this homework was copied from Tea.

**Comment by razvanperial** [comment]
> I have a strong suspicion that this homework was copied from Tea.

I didn't copy it, but we did do it together last week, hence why they might look similar. I understood everything we did.

**Comment by kajigor** [comment]
You can read how to parse arithmetic in the tutorial: https://markkarpov.com/tutorial/megaparsec.html

**Comment by kajigor** [comment]
Either, Let, Tests -- ok 
Arithmetic,  Proof tree -- not done.

**Pull request closed without merging**
